[2024-05-20T08:36:47.578+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T08:36:47.609+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_api_data_and_write_to_files.write_to_txt scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-20T08:36:47.619+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_api_data_and_write_to_files.write_to_txt scheduled__2024-05-14T00:00:00+00:00 [queued]>
[2024-05-20T08:36:47.622+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-05-20T08:36:47.643+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): write_to_txt> on 2024-05-14 00:00:00+00:00
[2024-05-20T08:36:47.653+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=325) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T08:36:47.656+0000] {standard_task_runner.py:63} INFO - Started process 327 to run task
[2024-05-20T08:36:47.656+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_api_data_and_write_to_files', 'write_to_txt', 'scheduled__2024-05-14T00:00:00+00:00', '--job-id', '1629', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_2.py', '--cfg-path', '/tmp/tmppidhw0nr']
[2024-05-20T08:36:47.659+0000] {standard_task_runner.py:91} INFO - Job 1629: Subtask write_to_txt
[2024-05-20T08:36:47.710+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_api_data_and_write_to_files.write_to_txt scheduled__2024-05-14T00:00:00+00:00 [running]> on host 0391a550332e
[2024-05-20T08:36:47.809+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sinta' AIRFLOW_CTX_DAG_ID='fetch_api_data_and_write_to_files' AIRFLOW_CTX_TASK_ID='write_to_txt' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T00:00:00+00:00'
[2024-05-20T08:36:47.811+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T08:36:47.823+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-20T08:36:47.824+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T08:36:47.834+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=fetch_api_data_and_write_to_files, task_id=write_to_txt, run_id=scheduled__2024-05-14T00:00:00+00:00, execution_date=20240514T000000, start_date=20240520T083647, end_date=20240520T083647
[2024-05-20T08:36:47.871+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T08:36:47.892+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-20T08:36:47.896+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
